### ISSUE TITLE
node_module version error when testing grammar inside atom-beta...

### ISSUE THREAD

**Issue by clojj** [tree-sitter/tree-sitter-haskell#10]
getting this, when I do
- `npm run-script build` inside tree-sitter-haskell
- `apm-beta rebuild` inside language-haskell (the --dev linked atom-package that is using /tree-sitter-haskell as a subdir inside /grammars)

![atom-beta](https://user-images.githubusercontent.com/4367963/37389673-8065e3f6-2765-11e8-88a3-496173a3be67.png)

installing this in devDependencies `electron-rebuild": "^1.7.3`
and running `./node_modules/.bin/electron-rebuild --version 1.7.11 --force` inside the tree-sitter-... module resolved this error for me

...so is using npm's 'electron-rebuild' the valid solution for this

**Comment by maxbrunsfeld** [comment]
You should just need to run `apm rebuild` in the `language-haskell` folder.

**Comment by rewinfrey** [comment]
@clojj can you confirm if `apm rebuild` was successful for you?

**Comment by clojj** [comment]
I will check that asap...

**Comment by rewinfrey** [comment]
@clojj circling back here, was your check for this successful?
