### ISSUE TITLE
Upgrade node-gyp dependency

### ISSUE THREAD

**Issue by pokey** [tree-sitter/tree-sitter-haskell#104]
We're getting some compilation errors on some of our developer's machines due to the old node-gyp version pulled in here. Would it be possible to upgrade that dependency version? Might be worth upgrading nan at the same time in case there's peer issue there

**Comment by tek** [comment]
I've set it to a generous range, please tell me if that's fine for your purpose

**Comment by pokey** [comment]
I think this will do, thanks!
