### ISSUE TITLE
exp_section_right not parsed when containing a hash

### ISSUE THREAD

**Issue by felixroos** [tree-sitter/tree-sitter-haskell#108]
an expression like `(+ x) y` is [parsed correctly](https://felixroos.github.io/haskell-tree-sitter-playground/#KCsgeCkgeQ==), whereas `(# x) y` [yields an error](https://felixroos.github.io/haskell-tree-sitter-playground/#KCMgeCkgeQ==). Interestingly, [it works when prefixing a space](https://felixroos.github.io/haskell-tree-sitter-playground/#KCAjIHgpIHk=). I guess this must be a bug?

**Comment by tek** [comment]
yeah the grammar behaves as if `UnboxedTuples` is always enabled, in which case `(#` is a parse error in GCC as well if not followed by a closing `#)`.
I haven't figured out a way to support both so far; this is complicated even further by the fact that symbolic operators are handled in the C extension code, so I doubt that this is feasible.

**Comment by yaxu** [comment]
That's a shame, `#` is used as an operator quite often in Haskell, including in the popular diagrams and tidal libraries.

**Comment by felixroos** [comment]
awesome, thanks so much for all your work! I can confirm this now works on my end :) [it seems to chew everything i throw at it](https://felixroos.github.io/haskell-tree-sitter-playground/#ZDEgJCBqdXgnIFtpZCxyZXYsKCMgc3BlZWQgMildICQgZXZlcnkgMiAoIjwwLjI1IDAuMTI1IDAuNT4iIDx+KSAkIHNvdW5kICJiZCoyIFtbfiBsdF0gc246M10gbHQ6MSBbaHQgbXQqMl0iCiAgIyBzcXVpeiAiPDEgMi41IDI+IgogICMgcm9vbSAoc2xvdyA0ICQgcmFuZ2UgMCAwLjIgc2F3KQogICMgc3ogMC41CiAgIyBvcmJpdCAx)
