### ISSUE TITLE
Please help me steal your scanner 

### ISSUE THREAD

**Issue by banacorn** [tree-sitter/tree-sitter-haskell#11]
Greetings!

I'm working on a tree-sitter grammar for Agda, a language whose syntax is heavily influenced by Haskell. Like Haskell, Agda relies on spaces for indentation, which requires some scanner preprocessing magic. And that leads me to the magical scanner you've built for Haskell.

However, I've failed to transplant the scanner to Agda.
Here's what I've done:
1. copy `src/scanner.cc` to the corresponding location at `tree-sitter-agda` and replace all occurrences of `haskell` to `agda`.
2. add `"src/scanner.cc"` to `binding.gyp` at `tree-sitter-agda`.
3. copy the *externals* from `grammar.js`.

I get the following error message when building the project.

```
> tree-sitter-agda@1.0.0 build-scanner /Users/banacorn/node/tree-sitter-agda
> node-gyp build --debug

  CC(target) Debug/obj.target/tree_sitter_agda_binding/src/parser.o
../src/parser.c:26238:43: error: use of undeclared identifier 'sym__layout_semicolon'
  [ts_external_token__layout_semicolon] = sym__layout_semicolon,
                                          ^
../src/parser.c:26239:44: error: use of undeclared identifier 'sym__layout_open_brace'
  [ts_external_token__layout_open_brace] = sym__layout_open_brace,
                                           ^
../src/parser.c:26240:45: error: use of undeclared identifier 'sym__layout_close_brace'
  [ts_external_token__layout_close_brace] = sym__layout_close_brace,
                                            ^
../src/parser.c:26258:6: error: use of undeclared identifier 'sym__layout_semicolon'
    [sym__layout_semicolon] = ACTIONS(1),
     ^
../src/parser.c:26259:6: error: use of undeclared identifier 'sym__layout_open_brace'
    [sym__layout_open_brace] = ACTIONS(1),
     ^
../src/parser.c:26260:6: error: use of undeclared identifier 'sym__layout_close_brace'
    [sym__layout_close_brace] = ACTIONS(1),
     ^
6 errors generated.
make: *** [Debug/obj.target/tree_sitter_agda_binding/src/parser.o] Error 1
```

Could you please point out where I may have done wrong? Thanks!

**Comment by banacorn** [comment]
I've found what may have caused the problem:

* The build would succeed if the *externals* were left empty in `grammar.js`.
* The build would fail if the *externals* were asserted but **not used** in the *rules* in `grammar.js`.
* The build would succeed if the *externals* were asserted and **used** in the *rules* in `grammar.js`.

**Comment by maxbrunsfeld** [comment]
Yeah, sorry about that confusing behavior. I have an issue for it, but haven't had time to fix it yet: https://github.com/tree-sitter/tree-sitter/issues/141.
