### ISSUE TITLE
Typed Template Haskell quotations / splices not handled correctly

### ISSUE THREAD

**Issue by kosmikus** [tree-sitter/tree-sitter-haskell#116]
GHC with `TemplateHaskell` allows typed quotations and splices, written
```
[|| x ||]
```
and
```
$$(foo bar)
```
or just
```
$$x
```

Looks like the tree-sitter parser currently handles this incorrectly, breaking syntax highlighting in rather substantial ways for files containing these constructs.

I looked briefly whether there's a very quick fix, but unfortunately it looks like this requires adapting the scanner.

**Comment by tek** [comment]
Added to the TODO list for my in-progress redesign, and fixed the most egregious bug for now.

But I don't see what's broken with the typed splices – do you have an example?

**Comment by tek** [comment]
cool, thanks for the report!
