### ISSUE TITLE
use es6 to write a generator.js

### ISSUE THREAD

**Issue by srghma** [tree-sitter/tree-sitter-haskell#132]
AFAIK its possible to rewrite generator.js on es6 and use `import/export` to improve type safety

I did it in https://github.com/postsolar/tree-sitter-purescript/pull/23 and in https://github.com/kayhide/tree-sitter-idris/pull/3

but I dont know that to replace `require('.')`

https://github.com/tree-sitter/tree-sitter-haskell/blob/70ea0757986ea58a0d39ddfcd9d791beadeb0f43/bindings/node/binding_test.js#L8

with

**Comment by srghma** [comment]
probably `require("./index.cjs")`

**Comment by amaanq** [comment]
ES6 is not supported, we cannot use it since we cannot declare the package as a module, and we cannot use it in standalone file mode until node 20.

**Comment by srghma** [comment]
does it mean that it will become feasible to rewrite tree-sitter-haskell to es6 using `.mjs` extension at 30 Apr 2025?

https://endoflife.date/nodejs

**Comment by amaanq** [comment]
Yes.
