### ISSUE TITLE
Nested multi-line comments not parsing

### ISSUE THREAD

**Issue by rewinfrey** [tree-sitter/tree-sitter-haskell#17]
Currently the grammar does not support nested multi-line comments:

```haskell
{-
  {-
  -}
-}
```

And also errors when parsing pragmas within comments:

```haskell
{-
{-# INLINE a #-}
-}
```

The external scanner will need to handle comments in a similar way as the tree-sitter [OCaml scanner](https://github.com/tree-sitter/tree-sitter-ocaml/pull/1/files).

**Comment by tek** [comment]
works now!
