### ISSUE TITLE
Grammar does not fully support -XBlockArguments extension

### ISSUE THREAD

**Issue by patrickt** [tree-sitter/tree-sitter-haskell#22]
GHC 8.6 comes with an extension, “block arguments”, that entails a drastic change to the parser. You can find the [change specification here](https://github.com/ghc-proposals/ghc-proposals/blob/master/proposals/0010-block-arguments.rst), but the tl;dr is that you can now often omit parentheses and `$` invocations associated with `do` blocks:

```
local f do
  thing1
  thing2
```

rather than

```
local f $ do
  thing1
  thing2
```

This has drastic effects on the grammar—in the words of the proposal author:
> Unless a special care is taken, an implementation will add a large number of shift-reduce conflicts to the parser, due to the reliance on the meta-rule mentioned above

This is a nontrivial change, but it’s one we should ultimately make.

**Comment by patrickt** [comment]
This is fixed

**Comment by tek** [comment]
nope, `let` and `if` are still missing!

**Comment by tek** [comment]
now it's fixed :sweat_smile:
