### ISSUE TITLE
Update on the state of the grammar

### ISSUE THREAD

**Issue by rewinfrey** [tree-sitter/tree-sitter-haskell#27]
Today @maxbrunsfeld and I met to talk about the current state of the Haskell grammar. We were interested in trying to get master back to a happy state. However, after untangling some of the conflicts with the grammar we found the remaining conflicts were increasing in complexity, which prompted us to re-evaluate our approach to parsing Haskell.

The original goal for this grammar was to be able to parse 100% of [semantic](https://github.com/github/semantic), which is an open source program analysis library we maintain and use at GitHub. Semantic uses several [default language extensions](https://github.com/github/semantic/blob/05edc308d0912223aaad7eb5d51c5642892b60c5/semantic.cabal#L28-L41) as well as additional [language extensions](https://github.com/github/semantic/blob/05edc308d0912223aaad7eb5d51c5642892b60c5/src/Diffing/Algorithm.hs#L1) in specific modules. Supporting these language extensions is a great goal, but adds a considerable amount of complexity to the grammar in terms of the number of productions used and handling the conflicts they can generate.

Max and I agreed that the current state of the grammar is extremely complex, including the external scanner. As more and more language extension support was added during the initial development of the grammar, the number of conflicts increased, and has the unfortunate side-effect of making it very hard to reason about how to fix conflicts or make changes.

I proposed to start a fresh grammar targeting only Haskel 2010 with an external scanner for correctly parsing Haskell's whitespace sensitive layout rules. From there, Max and I think a layered strategy to support the most common language extensions would be appropriate (similar to the way the [typescript parser](https://github.com/tree-sitter/tree-sitter-typescript/blob/2573038b6c77840618df17064800c914234207cb/common/define-grammar.js#L23-L25) works in conjunction with the javascript parser). We think this approach, with an emphasis on long-term maintainability, will make it easier for future iterations to make changes to the grammar, support new language extensions, and also make it easier for community contributions. Max and I also agree that it may not be possible for tree-sitter to fully support all of Haskell's language extensions as tree-sitter is a generic incremental parsing library, and Haskell is one of the more complex programming languages because of its language extension system. Time and experience will tell.

@maxbrunsfeld please feel free to include any other important points I may have left out. 🙇

**Comment by xylix** [comment]
I tried git cloning and running `tree-sitter generate` on this project, but it fails. Is this the unhappy state that master is in? Did anyone ever figure out some good approach for going forward with tree-sitter parsing haskell?

**Comment by rewinfrey** [comment]
This is superseded by https://github.com/tree-sitter/tree-sitter-haskell/pull/29 and no longer valid. Many of the previous conflicts described in this issue appear to be resolved with a more extensive [`scanner.cc`](https://github.com/tree-sitter/tree-sitter-haskell/blob/master/src/scanner.cc). Awesome work by @tek to rewrite the grammar!
