### ISSUE TITLE
It would be great to have a list of supported language extensions in the readme

### ISSUE THREAD

**Issue by expipiplus1** [tree-sitter/tree-sitter-haskell#36]
I see that LambdaCase, ScopedTypeVariables and DataKinds are mentioned in the test directory. There are also references in other issues to template Haskell.

**Comment by tek** [comment]
good idea!

**Comment by tek** [comment]
hey @expipiplus1 , I added that list. please close if you find it satisfactory.

**Comment by expipiplus1** [comment]
Amazing, thanks!
