### ISSUE TITLE
Not in haskell, when ghcide exists

### ISSUE THREAD

**Issue by AusCyberman** [tree-sitter/tree-sitter-haskell#39]
It should be written in haskell and compiled to an object file

**Comment by MatthijsBlom** [comment]
Perhaps you are looking for tree-sitter's [Haskell bindings](https://github.com/tree-sitter/haskell-tree-sitter)?

**Comment by AusCyberman** [comment]
> Perhaps you are looking for tree-sitter's [Haskell bindings](https://github.com/tree-sitter/haskell-tree-sitter)?

Nope, the tree sitter parser should have been written in haskell for easy integration with existing technology available as keeping up with language extensions and inconsistency would lag behind as opposed to HLS
