### ISSUE TITLE
scanner .... handling of layout_ symbols not clear

### ISSUE THREAD

**Issue by clojj** [tree-sitter/tree-sitter-haskell#4]
In the scanner I don't get this part.
Especially, what is `lookahead == 0` ?
I don't see the connection that should exist between newlines/indentation and the LAYOUT_SEMICOLON.

...

```
if (lexer->lookahead != '\n') return false;
    advance(lexer); 

    bool next_token_is_comment = false;
    uint32_t indent_length = 0;
    for (;;) {
      if (lexer->lookahead == '\n') {
        indent_length = 0;
        advance(lexer);
      } else if (lexer->lookahead == ' ') {
        indent_length++;
        advance(lexer);
      } else if (lexer->lookahead == '\t') {
        indent_length += 8;
        advance(lexer);
      } else if (lexer->lookahead == 0) {
        if (valid_symbols[LAYOUT_SEMICOLON]) {
          lexer->result_symbol = LAYOUT_SEMICOLON;
          return true;
        }
        if (valid_symbols[LAYOUT_CLOSE_BRACE]) {
          lexer->result_symbol = LAYOUT_CLOSE_BRACE;
          return true;
        }
        return false;
      } else {
        if (lexer->lookahead == '-' || lexer->lookahead == '{') {
          advance(lexer);
          next_token_is_comment = lexer->lookahead == '-';
        }
        break;
      }
    }
...

```

**Comment by maxbrunsfeld** [comment]
> what is `lookahead == 0`?

In this context `0` (the null character) means we are at the end-of-file.

> I don't see the connection that should exist between newlines/indentation and the `LAYOUT_SEMICOLON`.

This code adapts haskell's [layout rules](https://www.haskell.org/onlinereport/haskell2010/haskellch2.html#x7-210002.7) (which are [formally defined](https://www.haskell.org/onlinereport/haskell2010/haskellch10.html#x17-17800010.3) as a haskell function that transforms an entire list of tokens) into Tree-sitter's tokenization paradigm, in which we tokenize *on-demand*, during the process of parsing (as opposed to tokenizing the entire file in advance before we begin parsing).

The three elements of haskell's layout rules are the automatic insertion of semicolons, open braces and close braces. In this code, we refer to those tokens as `LAYOUT_SEMICOLON`, `LAYOUT_OPEN_BRACE` and `LAYOUT_CLOSE_BRACE`.

Our scanner carries as state an `indent_length_stack` that corresponds loosely to the 'layout contexts' in the formal specification of the layout algorithm. In addition, sometimes, the scanner discovers that it needs to insert *multiple* tokens in a certain place. For example, when it finds an outdent, it may need to first insert a `LAYOUT_SEMICOLON` token, then one or more `LAYOUT_CLOSE_BRACE` tokens. But each call to the scanner's `scan` method can only return *one* token. This is why the scanner carries its second piece of state: the `queued_close_brace_count`.

**Comment by clojj** [comment]
> In this context 0 (the null character) means we are at the end-of-file.
are you saying that at the moment when the parser request for more tokens, the end-of-file marker is in the middle of the source, for example in the nth clause of a let statement ?

**Comment by maxbrunsfeld** [comment]
> are you saying that at the moment when the parser request for more tokens, the end-of-file marker is in the middle of the source, for example in the nth clause of a let statement ?

No, this is just a check to see if we are actually at the end of the file. This check will return true at the end of the last declaration in a file, for example.

**Comment by clojj** [comment]
hm... ok
have to check this layout rule once again... I thought these virtual semicolons had something to do with newlines

**Comment by clojj** [comment]
I still don't get why end-of-file relates in any way to the layout-semicolon.

citation from the layout rule:
"... if it is indented the same amount, then a new item begins (a semicolon is inserted); and if it is indented less, then the layout list ends (a close brace is inserted). If the indentation of the non-brace lexeme immediately following a where, let, do or of is less than or equal to the current indentation level, then instead of starting a layout, an empty list “{}” is inserted, and layout processing occurs for the current level (i.e. insert a semicolon or close brace)."

**Comment by maxbrunsfeld** [comment]
Take the following code:

```hs
module Foo(bar, baz) where
bar = 1
baz = 2 
```

this is equivalent to:

```hs
module Foo(bar) where {
bar = 1;
baz = 2
}
```

A close brace is inserted at the end of the file in this case. I don't exactly understand your question. Does that answer it?

**Comment by clojj** [comment]
ok, but why is the semicolon handled by eof too ?

**Comment by clojj** [comment]
I was probably looking for this, sorry... so I test this logic in relation to the range-issue

![semicolon](https://user-images.githubusercontent.com/4367963/37000499-eb8f9a8a-20c3-11e8-8a2c-bca66338a69d.png)

**Comment by clojj** [comment]
currently the range for the 2nd variable-binding is this
![let-stmt1](https://user-images.githubusercontent.com/4367963/37000968-515eba52-20c5-11e8-8dc8-7985b74e3893.png)

but what I am expecting is this range
![let-stmt2](https://user-images.githubusercontent.com/4367963/37000974-581ec878-20c5-11e8-847b-59f61a58070a.png)

**Comment by clojj** [comment]
Maybe the '\n' scanning is the reason for this,as the range covers the previous newline (?)
The layout_semicolon is actually inserted just before the "z2" variable, so it should be ok I guess..

**Comment by clojj** [comment]
closed in favor of a new issue with more concise description of the underlying problem
