### ISSUE TITLE
Published most recent version to npm

### ISSUE THREAD

**Issue by wenkokke** [tree-sitter/tree-sitter-haskell#50]
This package hasn't been published to npm in a while, and the most recently published version no longer compiles with the recent versions of tree-sitter.

Would be possible to publish a more recent version? What is currently blocking a new version release?

**Comment by tek** [comment]
@patrickt @maxbrunsfeld 

how do we do this?

**Comment by 414owen** [comment]
Looks like @maxbrunsfeld is a collaborator on the `npm` package.  
@wenkokke Do you want to wait for https://github.com/tree-sitter/tree-sitter-haskell/issues/69, or is your ERROR node non-fatal?

**Comment by wenkokke** [comment]
We cannot release a new version until tree-sitter does, as we'll need to list the very latest version in our package.json.

**Comment by wenkokke** [comment]
The new version of tree-sitter is out!
https://github.com/tree-sitter/tree-sitter/releases/tag/v0.20.4

We can publish a release which uses that version now :)

**Comment by Thaodan** [comment]
The last tagged version doesn't even build anymore (requires 528013056ee60db47699ce500b26f76f8b027aa0 to build again).

Please tag a new release.

**Comment by tek** [comment]
@Thaodan I bumped a tag.

With my upcoming rewrite of the project, I will set the version to 1.0 and do regular uploads to npm, as soon as https://github.com/tree-sitter/tree-sitter/issues/3080 is handled.

**Comment by Thaodan** [comment]
Thank. Help me packaging the grammar with rpm.

**Comment by Thaodan** [comment]
You tagged 0.15.0 as 0.15.0 and v15.0.0 please remove the first
redundant tag.

**Comment by tek** [comment]
oh hmm maybe the release workflow tagged this as well
