### ISSUE TITLE
problem with multiline comments

### ISSUE THREAD

**Issue by clojj** [tree-sitter/tree-sitter-haskell#7]
Having the closing '-}' in a new line, the multiline comment is parsed correctly:
![multiline-comment-ok](https://user-images.githubusercontent.com/4367963/37328625-283af984-269b-11e8-9e31-9f8de70d5461.png)

But if it is on the same line as some comment, it is parsed as ERROR
![multiline-comment-error](https://user-images.githubusercontent.com/4367963/37328708-7627495e-269b-11e8-902b-6c26d9b3593e.png)
![multiline-comment-error2](https://user-images.githubusercontent.com/4367963/37328717-7ac67746-269b-11e8-999d-563def73d673.png)

**Comment by clojj** [comment]
sorry, didn't have time to propose some corpus test-cases yet..

**Comment by rewinfrey** [comment]
@clojj thanks for finding this! I've pushed a fix in https://github.com/tree-sitter/tree-sitter-haskell/commit/9ad3593ec1a4bea0d34ff1c9e85736224fb5d9b4 that corrects this behavior. There are also some additional test cases I've added that are related to your PR (specifically https://github.com/tree-sitter/tree-sitter-haskell/pull/8#discussion_r174262302).
