### ISSUE TITLE
Grammar defines trailing whitespace as part of lambda case statement

### ISSUE THREAD

**Issue by wenkokke** [tree-sitter/tree-sitter-haskell#74]
The `exp_lambda_case` node associated with the first definition includes the trailing white space:

![Screenshot 2022-03-07 at 15 47 50](https://user-images.githubusercontent.com/3983973/157068182-d9c3664d-2c79-4a4b-ad18-342a891f82c7.png)

This results, for example, in incorrect deletions when operating based off the AST, with a deletion of the lambda case expression resulting in:

![Screenshot 2022-03-07 at 15 50 06](https://user-images.githubusercontent.com/3983973/157068514-795e47b7-5ec1-41d7-a1ba-a2a61f35044f.png)

**Comment by tek** [comment]
huh. are you positive this doesn't happen with any other nodes?
I remember fixing this problem for comments, I thought I scrutinized every single whitespace parser for similar behaviour at that time.
Could this be a regression from the scanner translation to C?
In any case, I'll investigate.

btw, what's the deal with those ornaments on top of every token? :upside_down_face:

**Comment by wenkokke** [comment]
It might be happening with other notes that I haven’t discovered yet.

**Comment by wenkokke** [comment]
> btw, what's the deal with those ornaments on top of every token? 🙃

https://marketplace.visualstudio.com/items?itemName=pokey.cursorless

it’s why I’m reliant on this grammar, for voice coding

**Comment by tek** [comment]
wow, never seen anything like that before. interesting
