### ISSUE TITLE
Parse errors when using DerivingVia

### ISSUE THREAD

**Issue by luc-tielen** [tree-sitter/tree-sitter-haskell#76]
This happens to me when using neovim with nvim-treesitter.

Steps to reproduce:

1. git clone https://github.com/luc-tielen/souffle-haskell
2. open the file: "DerivingViaSpec.hs", notice the highlighting is not fully working
3. in neovim: `:TSPlaygroundToggle`, errors show up in the AST.

Probably some uncovered case because it is using a lot of extensions/type-level features?

**Comment by tek** [comment]
ah, because it expects parentheses

**Comment by tek** [comment]
one character fix :)

**Comment by luc-tielen** [comment]
Verified that it works, thanks!
