### ISSUE TITLE
"undefined symbol: tree_sitter_haskell_external_scanner_create" when running "tree-sitter test"

### ISSUE THREAD

**Issue by Kleidukos** [tree-sitter/tree-sitter-haskell#94]
Version: tree-sitter 0.20.7

Hi! I'm trying to re-use the grammar for learning with a haskell-like language, an I get this message when I run `tree-sitter test`:

```
❯ tree-sitter test          
Error opening dynamic library "/home/hecate/.cache/tree-sitter/lib/haskell.so"

Caused by:
    /home/hecate/.cache/tree-sitter/lib/haskell.so: undefined symbol: tree_sitter_haskell_external_scanner_create
```

It's fairly hard to look up on search engines. Any idea what could be the cause?

**Comment by tek** [comment]
hm, no clue. tree-sitter too old maybe? is that a fresh checkout? did you try deleting that `haskell.so`?

**Comment by tek** [comment]
ah, how do you do that?

**Comment by tek** [comment]
hmm there is a submodule in the repo here: https://github.com/tree-sitter/haskell-tree-sitter/tree/master/tree-sitter-haskell/vendor
that is from 2018, maybe that causes a conflict? how did you add the grammar files?

**Comment by Kleidukos** [comment]
Just by copying them in my own repo, reproducing the `grammar/` directory hierarchy. But the submodule is not yet a problem because I'm hitting the error on `tree-sitter test` and not from Haskell. I'm closing this issue now and I'll re-open when I have more concrete stuff to bring. For now I'll be using a full clone of the repo as a starting point. :)

**Comment by tek** [comment]
good luck!
